build(commit): disable 'header too long'

diff --git a/automation/commit-msg b/automation/commit-msg
--- a/automation/commit-msg
+++ b/automation/commit-msg
@@ -24,7 +24,7 @@ if ! head -1 "$1" | grep -qE "^(build|chore|ci|docs|feat|fix|perf|refactor|resou
 	echo "scopes: common, config, sampleapp, vault, logtovault, sink" >&2
     exit 1
 fi
-if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
-    echo "Aborting commit. Your commit message header is too long." >&2
-    exit 1
-fi
+#if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
+#    echo "Aborting commit. Your commit message header is too long." >&2
+#    exit 1
+#fi
