build(commit): add hints for commit convention in the error message

diff --git a/automation/commit-msg b/automation/commit-msg
--- a/automation/commit-msg
+++ b/automation/commit-msg
@@ -6,6 +6,22 @@ if ! head -1 "$1" | grep -qE "^(build|chore|ci|docs|feat|fix|perf|refactor|resou
     echo "<body>" >&2
     echo "<BLANK LINE>" >&2
     echo "<footer>" >&2
+    echo " " >&2
+    echo "Types:" >&2
+    echo "- build: Changes that affect the build system or external dependencies" >&2
+    echo "- ci: Changes to the CI configuration files and scripts" >&2
+    echo "- chore: Other changes that don't modify src or test files; no production code change" >&2
+    echo "- docs: documentation-only changes" >&2
+    echo "- resource: resource changes; no production code change" >&2
+    echo "- feat: new feature for the user (not a new feature for build script)" >&2
+    echo "- fix: bug fix for the user (not a fix to a build script)" >&2
+    echo "- perf: A code change that improves performance" >&2
+    echo "- revert: Reverts a previous commit" >&2
+    echo "- refactor: A code change that neither fixes a bug nor adds a feature" >&2
+    echo "- style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc); no production code change" >&2
+    echo "- test: Adding missing tests or correcting existing tests; no production code change" >&2
+    echo " " >&2
+	echo "scopes: common, config, sampleapp, vault, logtovault, sink" >&2
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
